
INFO:root:Epoch 1
/home/brett/anaconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py:558: UserWarning: This DataLoader will create 10 worker processes in total. Our suggested max number of worker in current system is 4, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  warnings.warn(_create_warning_msg(
INFO:root:Epoch [1/50], Validation Loss: 0.4888
INFO:root:Epoch 2
INFO:root:Epoch [2/50], Validation Loss: 0.4888
INFO:root:Epoch 3
INFO:root:Epoch [3/50], Validation Loss: 0.4889
INFO:root:Epoch 4
INFO:root:Epoch [4/50], Validation Loss: 0.4889
INFO:root:Epoch 5
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7f8eae829790>
Traceback (most recent call last):
  File "/home/brett/anaconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1479, in __del__
    self._shutdown_workers()
  File "/home/brett/anaconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1443, in _shutdown_workers
    w.join(timeout=_utils.MP_STATUS_CHECK_INTERVAL)
  File "/home/brett/anaconda3/lib/python3.8/multiprocessing/process.py", line 149, in join
    res = self._popen.wait(timeout)
  File "/home/brett/anaconda3/lib/python3.8/multiprocessing/popen_fork.py", line 44, in wait
    if not wait([self.sentinel], timeout):
  File "/home/brett/anaconda3/lib/python3.8/multiprocessing/connection.py", line 931, in wait
    ready = selector.select(timeout)
  File "/home/brett/anaconda3/lib/python3.8/selectors.py", line 415, in select
    fd_event_list = self._selector.poll(timeout)
KeyboardInterrupt:
Process Process-1:
Traceback (most recent call last):
  File "/home/brett/anaconda3/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/brett/anaconda3/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/brett/Desktop/tutorials/ijepa/ijepa/main_ijepa.py", line 62, in process_main
    app_main(args=params)
  File "/home/brett/Desktop/tutorials/ijepa/ijepa/src/train.py", line 392, in main
    # val_loss = validate(val_loader, encoder, predictor=target_encoder)
  File "/home/brett/Desktop/tutorials/ijepa/ijepa/src/train.py", line 300, in validate
KeyboardInterrupt